[package]
name = "parceljs"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
includedir = "0.5.0"
phf = "0.7.24"

[build-dependencies]
includedir_codegen = "0.5.0"
