name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@dd7556a6905c9e8fa54f9907194f55f887f5db0d # main
