name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@5af890fc12f7705d94c30dd561538cf363fddfa3 # main
