name: Release

on:
  push:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout, and to be able to create a release

jobs:
  release:
    uses: SpiralP/github-reusable-workflows/.github/workflows/release.yml@779c0da2b5f763494dffddf0bbfb4884d1642ba6 # main
